apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-sender
  namespace: calendar
  labels:
    app: calendar-sender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-sender
  template:
    metadata:
      labels:
        app: calendar-sender
    spec:
      containers:
        - name: sender
          image: sender:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: calendar-config
            - secretRef:
                name: calendar-secrets
      restartPolicy: Always