apiVersion: v1
kind: Service
metadata:
  name: calendar-sender
  namespace: calendar
spec:
  selector:
    app: calendar-sender
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8082
