apiVersion: v1
kind: ConfigMap
metadata:
  name: calendar-config
  namespace: calendar
data:
  DB_HOST: "postgres-postgresql"
  DB_PORT: "5432"
  DB_USER: "user"
  DB_NAME: "calendar"
  LOG_LEVEL: "debug"
  TZ: "UTC"