// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/event/create": {
            "post": {
                "description": "Create a new calendar event",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "events"
                ],
                "summary": "Create a new event",
                "parameters": [
                    {
                        "description": "Event data",
                        "name": "event",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/internalhttp.CreateEventRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/internalhttp.CreateEventResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "internalhttp.CreateEventRequest": {
            "description": "Represents the request to create an event.",
            "type": "object",
            "properties": {
                "description": {
                    "type": "string",
                    "example": "Discuss project roadmap"
                },
                "endTime": {
                    "type": "integer",
                    "example": 1717293600
                },
                "notifyBefore": {
                    "type": "integer",
                    "example": 600
                },
                "startTime": {
                    "type": "integer",
                    "example": 1717290000
                },
                "title": {
                    "type": "string",
                    "example": "Team Meeting"
                },
                "userId": {
                    "type": "string",
                    "example": "id1234"
                }
            }
        },
        "internalhttp.CreateEventResponse": {
            "description": "Represents a successful event creation response.",
            "type": "object",
            "properties": {
                "event": {
                    "$ref": "#/definitions/internalhttp.CreateEventRequest"
                },
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/.",
	Schemes:          []string{},
	Title:            "Receipt Hub API",
	Description:      "This is a server for Calendar",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
