auth:
  username: user
  password: pass
  database: calendar

service:
  port: 5432

primary:
  resources:
    requests:
      memory: 256Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m