apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-api
  namespace: calendar
  labels:
    app: calendar-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-api
  template:
    metadata:
      labels:
        app: calendar-api
    spec:
      containers:
        - name: calendar
          image: calendar:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: calendar-config
            - secretRef:
                name: calendar-secrets
          env:
            - name: MIGRATE
              value: "true"
      restartPolicy: Always