apiVersion: v1
kind: Service
metadata:
  name: calendar-api
  namespace: calendar
spec:
  selector:
    app: calendar-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort
