http:
  host: localhost
  port: 8080
  readTimeout: "10s"
  writeTimeout: "10s"
  idleTimeout: "30s"
  readHeaderTimeout: "2s"

log:
  level: 'debug'

database:
  type: postgres
  dsn: "postgresql://postgres@localhost:5432/calendar?sslmode=disable"
  migrations: "migrations"
  timeout: "10s"

grpc:
  enable: true
  port: 50051