rabbitmq:
  host: "localhost"
  port: "5672"
  user: "guest"
  password: "guest"
  exchange: "notifications"

database:
  type: postgres
  dsn: "host=localhost port=5432 user=postgres password=postgres dbname=calendar sslmode=disable"

scheduler:
  interval: 10s
  retention_period: 8760h