apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-scheduler
  namespace: calendar
  labels:
    app: calendar-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-scheduler
  template:
    metadata:
      labels:
        app: calendar-scheduler
    spec:
      containers:
        - name: scheduler
          image: scheduler:develop
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: calendar-config
            - secretRef:
                name: calendar-secrets
      restartPolicy: Always