apiVersion: v1
kind: Service
metadata:
  name: calendar-scheduler
  namespace: calendar
spec:
  selector:
    app: calendar-scheduler
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
